### ISSUE TITLE
HotspotAutoLogin.pyw modules

### ISSUE THREAD

**Issue by fernhad** [denizsafak/HotspotAutoLogin#2]
hi I'm new to this technology which you created but during configuration of the module I'm facing a challenge where the import pystry module can't be called at the main.
Glad if you could cover me on this. 
Thank you for your time.

**Comment by denizsafak** [comment]
Did you run it from "run.bat"? Running the python file directly can cause problems. Can you explain how you get that error so I can test it myself?

**Comment by fernhad** [comment]
I ran the python file directly on my MicrosoftVS after I configured it.

**Comment by denizsafak** [comment]
You should run it using run.bat file. Just configure the config.json file, nothing more needed

**Comment by fernhad** [comment]
I am facing pystray module issue not being able to be found ..
Inoder to run from run.bat file which app should be used.

**Comment by denizsafak** [comment]
The program works only in Windows, If you don't want to use the .bat file you need to download the modules in the requirements.txt file, then try to run it directly. The bat file works only in Windows.

**Comment by fernhad** [comment]
finally thank you.
