### ISSUE TITLE
Allow customize is_internet_available from profile?

### ISSUE THREAD

**Issue by hkiairis-kinetix** [denizsafak/HotspotAutoLogin#4]
I seem hotspot which i would like to use is allow ping 8.8.8.8 without error even Wi-Fi is not login. Could it have some customize setting on profile which call curl/wget with expected wording inside response?

**Comment by denizsafak** [comment]
Thanks for the good idea, added "internet_check_url" feature to [HotspotAutoLogin v1.83](https://github.com/denizsafak/HotspotAutoLogin/releases/tag/hotspotautologin-v1.83)
